### ISSUE TITLE
couldn't find pc file warning

### ISSUE THREAD

**Issue by aleksandrach** [oliverepper/pjproject-apple-platforms-Demo#2]
If you try to run the project, it will return warning couldn't find pc file for pjproject-apple-platforms-SPM.

**Comment by oliverepper** [comment]
You need to do the following:

```sh
brew tap oliverepper/made && brew install pjproject-apple-platforms`
```

After you installed this. Xcode needs to restart because it only asks pkg-config once for the compiler configuration.

You can read more about the setup here:
https://oliver-epper.de/posts/managing-binary-dependencies-for-swift/

If you know al that already I guess restarting Xcode will do the trick.

**Comment by aleksandrach** [comment]
It fixed the issue. Thanks!
